### PR TITLE
Feature/423 bug bg overrides text

### LINKED ISSUE #423: Control "Background Color Classes" background override the text color
Currently, when the Background color of a section which has the class `sk-light-bg` or `sk-dark-bg` is updated using global color the text's color also overrides to value present in the background color instead of that the background color value should not override the text color.

### Dependency:
#424 

### Related to:
https://github.com/analogwp/style-kits-pro/issues/91

### PR DESCRIPTION
**Pull request by gvgvgvijayan**
Resolves #423

### CODE REVIEW

File: inc/elementor/sections/background-color-classes.php [hunk 1]
```diff
@@ -80,7 +80,7 @@ public function register_section( Controls_Stack $element, $section_id ) {
 					'{{WRAPPER}}' => '--ang_background_light_background: {{VALUE}};',
 					'{{WRAPPER}} .sk-light-bg:not(.elementor-column)' => 'background-color: {{VALUE}};',
 					'{{WRAPPER}} .sk-dark-bg .elementor-counter-title, {{WRAPPER}} .sk-dark-bg .elementor-counter-number-wrapper' => 'color: currentColor',
-					'{{WRAPPER}} .sk-light-bg.elementor-column > .elementor-element-populated' => 'background-color: {{VALUE}}; color: var(--ang_color_text_light)',
+					'{{WRAPPER}} .sk-light-bg.elementor-column > .elementor-element-populated' => 'background-color: {{VALUE}};',
```
Comment (mauryaratan) [inline inc/elementor/sections/background-color-classes.php:83]: I see you're removing the text color, but we're Text Light color applied on background color classes, with these removed how'd we apply Background Color Classes > Text color?

Comment (mauryaratan) [reply inc/elementor/sections/background-color-classes.php:83]: @gvgvgvijayan

Comment (gvgvgvijayan) [reply inc/elementor/sections/background-color-classes.php:83]: > I see you're removing the text color, but we're Text Light color applied on background color classes, with these removed how'd we apply Background Color Classes > Text color?

Added video message in slack product channel (https://analogwp.slack.com/archives/CJ72D4S03/p1605007628009200)
